<?php

namespace Imanghafoori\LaravelMicroscope\Tests\stubs;


class SomeFunction{


    public function _1(){
        var_dump("hello");
        dd("hello");
    }

    public function _2(){
        fn() => array_sum (
            [6, 9]
        );

        array_push([8 , 9 , array_sum([8 , 7], array_sum([9 , 8]))]);


        foreach( range(1, 8) as $i ){
            array_sum([9 , 8 , $i]);
        }

        echo " array_sum([9, 7]) ";
        echo ' array_sum([9, 7]) ';
    }

    public static function _3(){
        Foo::_1();
        Foo::_3();

        self::_3();

        var_dump("Foo::_3()");

        var_dump("{Foo::_3()}" . "_" . Foo::_3());

        Foo::_3(self:: _3 ());
        Foo::_3;
        Foo::_33;

    }

}
