<?php


namespace EasyPanelTest\Unit;


use EasyPanelTest\TestCase;
use EasyPanelTest\Dependencies\WithTranslatable;

class TranslatableTest extends TestCase
{
    private $translatable;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->translatable = new WithTranslatable();
    }

    /** @test * */
    public function it_adds_texts_in_happy_path(){
        $this->translatable->addText('EasyPanel');

        $this->assertContains('EasyPanel', $this->translatable->getTexts());
        $this->assertArrayHasKey('EasyPanel', $this->translatable->getTexts());
    }

    /** @test * */
    public function if_key_is_not_null_it_will_be_used(){
        $this->translatable->addText('Easy but Panel !', 'EasyPanel');

        $this->assertContains('Easy but Panel !', $this->translatable->getTexts());
        $this->assertArrayHasKey('EasyPanel', $this->translatable->getTexts());
    }

    public function if_key_exists_in_texts_it_wont_be_duplicated()
    {
        $this->translatable->addText('EasyPanel');
        $this->assertCount(1, $this->translatable->getTexts());
        $this->assertArrayHasKey('EasyPanel', $this->translatable->getTexts());

        $this->translatable->addText('EasyPanel');
        $this->assertCount(1, $this->translatable->getTexts());

        $this->translatable->addText('EasyPanel', 'EasyPanel');
        $this->assertCount(1, $this->translatable->getTexts());

        $this->translatable->addText('EasyPanel', 'CustomKey');
        $this->assertCount(2, $this->translatable->getTexts());
    }
}
